config/routes.rb
Rails.application.routes.draw do

  options = Rails.env.production? ? { path: "", constraints: { subdomain: 'es' }} : {}

  concern :pick do
    member do
      get :pick
      patch :pick, action: :update_pick
    end
  end

  concern :review do
    member do
      get :review
      patch :review, action: :update_review
    end
  end

  namespace :merchants, options do
    resource :merchant_session, path: "session"
    resource :merchant do
      get :forget_password
      match :verification_code, via: [:get, :post, :patch]
      match :confirm, via: [:post, :patch]

      get :password
      patch :password, action: :update_password
    end

    resource :note

    resources :orders, concerns: [:pick, :review] do
      resources :bids do
        member do
          get :pick
        end
      end

      collection do
        get :"pay/:id", action: :pay, as: :pay
      end

      member do
        post :pend
        post :cancel
        match :refund, via: [:get, :patch]
        match :notify, via: [:get, :post]
        get :result
        post :confirm
        post :rework
        get :revoke
        get :remark
        patch :remark, action: :update_remark
      end
    end

    namespace :hosting do
      resources :orders, concerns: [:pick, :review] do
        member do
          match :refund, via: [:get, :patch]
          post :confirm
          post :rework
          get :revoke
          get :remark
          patch :remark, action: :update_remark
          get :procedure_price
          patch :procedure_price, action: :update_procedure_price
        end
      end
    end

    resources :merchants
    resources :mechanics do
      member do
        post :follow
        post :unfollow
        get :remark
        patch :remark, action: :update_remark
        get :reviews
        get :"skills/:skill", action: :skill, as: :skill
      end
    end

    namespace :admin do
      resources :merchants do
        member do
          post :active
          post :inactive
        end
      end
      resources :orders do
        member do
          post :close
        end
      end
      resource :store
      resources :recharges do
        member do
          match :notify, via: [:get, :post]
          get :result
        end
      end
    end

    namespace :store do
      resources :orders
    end
    resource :store

    root to: "orders#new"
  end

  mount WeixinRailsMiddleware::Engine, at: "/"
  resource :user
  resource :user_session, path: "session" do
    post :verification_code
  end
  resource :user_group do
    get :weixin_qr_code
    get :users
  end
  resources :mechanics do
    member do
      get :follow
      get :unfollow
      get :reviews
    end
  end

  resources :orders, concerns: [:review] do
    resources :bids do
      member do
        get :pick
      end
    end

    collection do
      get :"pay/:id", action: :pay, as: :pay
      get :not_found
    end

    member do
      get :cancel
      get :refund
      post :notify
      get :result
      get :work
      patch :finish
      get :confirm
    end
  end

  resources :withdrawals

  namespace :admin do
    concern :confirm do
      collection do
        get :confirmed
      end
      member do
        post :confirm
      end
    end
    concern :cancel do
      collection do
        get :canceled
      end
      member do
        post :cancel
      end
    end
    concern :hide do
      collection do
        get :hidden
      end
      member do
        post :hide
        post :unhide
      end
    end
    concern :freeze do
      collection do
        get :frozen
      end
      member do
        post :freeze
      end
    end

    resource :administrator_session, path: "session"
    resource :administrator, only: [] do
      get :forget_password
      match :verification_code, via: [:get, :post, :patch]
      match :confirm, via: [:post, :patch]

      get :password
      patch :password, action: :update_password
    end

    resources :administrators do
      member do
        post :active
        post :inactive
      end
    end

    resources :users do
      member do
        post :mechanicize

        get :balance
        patch :balance, action: :update_balance
      end
    end
    resources :user_groups, concerns: [:confirm]
    resources :mechanics, concerns: [:hide] do
      resources :orders

      collection do
        get :import
        post :import, action: :create_import
      end

      member do
        post :clientize
      end
    end
    resources :merchants, concerns: [:confirm] do
      resources :orders

      member do
        post :active
        post :inactive
        get :settings
        post :settings, action: :update_settings
      end
    end
    resources :orders
    resources :refunds, concerns: [:confirm, :freeze]
    resources :withdrawals, concerns: [:confirm, :cancel] do
      collection do
        get :settings
        post :settings, action: :update_settings
      end
    end
    namespace :settings do
      resources :skills
      resources :brands
      resources :series, except: :show
    end

    root to: "users#index"
  end

  root to: "users#show"
end

app/models/administrator.rb
class Administrator < ApplicationRecord
  Config = YAML.load(ERB.new(File.read("#{Rails.root}/config/admin.yml")).result)[Rails.env]

  include MobileVerificationCode

  attr_accessor :current_password

  as_enum :role, admin: 0, operator: 1

  validates_presence_of :nickname

  def inactive!
    update_attribute(:active, false)
  end

  def active!
    update_attribute(:active, true)
  end

end

app/controllers/admin/administrators_controller.rb
class Admin::AdministratorsController < Admin::ApplicationController
  skip_before_action :authenticate!, only: [ :forget_password, :verification_code, :confirm ]
  before_action :redirect_user, except: [ :password, :update_password, :forget_password, :verification_code, :confirm ]
  before_action :find_admin, only: [ :show, :edit, :update, :password, :update_password ]

  def index
    @admins = Administrator.all
  end

  def new
    @admin = Administrator.new
  end

  def create
    @admin = Administrator.new(admin_params)
    @admin.skip_send_verification_code
    if @admin.save
      redirect_to admin_administrators_path
    else
      render :new
    end
  end

  def active
    @admin.active!
    redirect_to_referer!
  end

  def inactive
    @admin.inactive!
    redirect_to_referer!
  end

  def forget_password
    set_redirect :password, password_admin_administrator_path
    @admin = Administrator.new
  end

  def verification_code
    mobile = session[:mobile] || params[:administrator][:mobile]
    @admin = Administrator.where(mobile: mobile).first_or_initialize
    if @admin.persisted?
      if @admin.reset_verification_code!
        flash.now[:notice] = "短信验证码已发送，请注意查收"
        session[:mobile] = nil
        render :verification_code
      else
        render :forget_password
      end
    else
      @admin.errors.add :base, "手机号码未注册"
      render :forget_password
    end
  rescue
    redirect_to forget_password_admin_administrator_path
  end

  def confirm
    @admin = Administrator.where(verification_code_params).first_or_initialize
    if @admin.persisted?
      @admin.confirm!

      admin_session = AdministratorSession.new(@admin)
      admin_session.save

      session[:verification_code] = true
      redirect! :password, admin_root_path
      clear_redirect :password
    else
      @admin.errors.add :verification_code, "错误"
      render :verification_code
    end
  end

  def update
    if @admin.update_attributes(admin_params)
      redirect_to admin_administrators_path
    else
      render :edit
    end
  end

  def update_password
    if session[:verification_code] || @admin.valid_password?(admin_params[:current_password])
      if @admin.update_attributes(admin_params)
        session[:verification_code] = nil
        flash[:success] = "修改密码成功"
        redirect_to admin_root_path
      else
        render :password
      end
    else
      @admin.errors.add :current_password, "错误"
      render :password
    end
  end

  private

    def find_admin
      @admin = if params[:id]
          Administrator.find(params[:id])
        else
          current_admin
        end
    end

    def admin_params
      params.require(:administrator).permit(:mobile, :nickname, :password, :password_confirmation,
        :current_password, :role)
    end

    def verification_code_params
      params.require(:administrator).permit(:mobile, :verification_code)
    end

end

app/views/admin/administrators/_form.html.erb
<div class="row">
  <div class="col-md-7">
    <%= bootstrap_simple_form_for([ :admin, @admin ]) do |f| %>
      <%= f.error_messages %>

      <%= f.input :nickname %>
      <%= f.input :mobile %>

      <%= f.input :password %>
      <%= f.input :password_confirmation %>

      <% unless current_admin == @admin %>
        <%= f.input :role, collection: enum_option_pairs(Administrator, :role) %>
      <% end %>

      <%= f.button :submit, "确定", class: "btn-primary pull-right" %>
    <% end %>
  </div>
</div>

app/views/admin/administrators/edit.html.erb
<h3 class="page-header">编辑管理员</h3>

<%= render "form" %>

app/views/admin/administrators/forget_password.html.erb
<h3 class="page-header">找回密码</h3>

<div class="row">
  <div class="col-md-7">
    <%= bootstrap_simple_form_for(@admin, url: verification_code_admin_administrator_path) do |f| %>
      <%= f.error_messages %>

      <%= f.input :mobile %>

      <%= f.button :submit, "验证手机", class: "btn-primary pull-right" %>
    <% end %>
  </div>
</div>

app/views/admin/administrators/index.html.erb
<h3 class="page-header">
  管理员管理
  <small><%= link_to "添加管理员", new_admin_administrator_path %></small>
</h3>

<%= index_for [ :admin, @admins ], class: "table table-hover data-tables" do |i| %>
  <%= i.attribute :nickname %>
  <%= i.attribute :mobile %>
  <%= i.attribute :login_count %>
  <%= i.attribute :current_login_at, format: :long %>
  <%= i.attribute :role do |admin| %>
    <%= te admin, :role %>
  <% end %>

  <%= i.actions :edit do |a| %>
    <% unless current_admin == i.object %>
      <% if i.object.active %>
        <%= a.action_link :inactive, url: inactive_admin_administrator_path(i.object), method: :post, confirm: "你确定要锁定这个账户？" %>
      <% else %>
        <%= a.action_link :active, url: active_admin_administrator_path(i.object), method: :post, confirm: "你确定要激活这个账户？" %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/admin/administrators/new.html.erb
<h3 class="page-header">添加管理员</h3>

<%= render "form" %>

app/views/admin/administrators/password.html.erb
<h3 class="page-header">修改密码</h3>

<div class="row">
  <div class="col-md-7">
    <%= bootstrap_simple_form_for(@admin, url: password_admin_administrator_path) do |f| %>
      <%= f.error_messages %>

      <% unless session[:verification_code] %>
        <%= f.input :current_password %>
      <% end %>

      <%= f.input :password %>
      <%= f.input :password_confirmation %>

      <%= f.button :submit, "确定", class: "btn-primary pull-right" %>
    <% end %>
  </div>
</div>

app/views/admin/administrators/verification_code.html.erb
<h3 class="page-header">验证手机</h3>

<div class="row">
  <div class="col-md-7">
    <%= bootstrap_simple_form_for(@admin, url: confirm_admin_administrator_path) do |f| %>
      <%= f.error_messages %>

      <%= f.hidden_field :mobile %>
      <%= f.input :verification_code, input_html: { value: nil } %>

      <%= f.button :submit, "验证手机", class: "btn-primary pull-right" %>
    <% end %>
  </div>
</div>