config/routes.rb
Rails.application.routes.draw do

  options = Rails.env.production? ? { path: "", constraints: { subdomain: 'es' }} : {}

  concern :pick do
    member do
      get :pick
      patch :pick, action: :update_pick
    end
  end

  concern :review do
    member do
      get :review
      patch :review, action: :update_review
    end
  end

  namespace :merchants, options do
    resource :merchant_session, path: "session"
    resource :merchant do
      get :forget_password
      match :verification_code, via: [:get, :post, :patch]
      match :confirm, via: [:post, :patch]

      get :password
      patch :password, action: :update_password
    end

    resource :note

    resources :orders, concerns: [:pick, :review] do
      resources :bids do
        member do
          get :pick
        end
      end

      collection do
        get :"pay/:id", action: :pay, as: :pay
      end

      member do
        post :pend
        post :cancel
        match :refund, via: [:get, :patch]
        match :notify, via: [:get, :post]
        get :result
        post :confirm
        post :rework
        get :revoke
        get :remark
        patch :remark, action: :update_remark
      end
    end

    namespace :hosting do
      resources :orders, concerns: [:pick, :review] do
        member do
          match :refund, via: [:get, :patch]
          post :confirm
          post :rework
          get :revoke
          get :remark
          patch :remark, action: :update_remark
          get :procedure_price
          patch :procedure_price, action: :update_procedure_price
        end
      end
    end

    resources :merchants
    resources :mechanics do
      member do
        post :follow
        post :unfollow
        get :remark
        patch :remark, action: :update_remark
        get :reviews
        get :"skills/:skill", action: :skill, as: :skill
      end
    end

    namespace :admin do
      resources :merchants do
        member do
          post :active
          post :inactive
        end
      end
      resources :orders do
        member do
          post :close
        end
      end
      resource :store
      resources :recharges do
        member do
          match :notify, via: [:get, :post]
          get :result
        end
      end
    end

    namespace :store do
      resources :orders
    end
    resource :store

    root to: "orders#new"
  end

  mount WeixinRailsMiddleware::Engine, at: "/"
  resource :user
  resource :user_session, path: "session" do
    post :verification_code
  end
  resource :user_group do
    get :weixin_qr_code
    get :users
  end
  resources :mechanics do
    member do
      get :follow
      get :unfollow
      get :reviews
    end
  end

  resources :orders, concerns: [:review] do
    resources :bids do
      member do
        get :pick
      end
    end

    collection do
      get :"pay/:id", action: :pay, as: :pay
      get :not_found
    end

    member do
      get :cancel
      get :refund
      post :notify
      get :result
      get :work
      patch :finish
      get :confirm
    end
  end

  resources :withdrawals

  namespace :admin do
    concern :confirm do
      collection do
        get :confirmed
      end
      member do
        post :confirm
      end
    end
    concern :cancel do
      collection do
        get :canceled
      end
      member do
        post :cancel
      end
    end
    concern :hide do
      collection do
        get :hidden
      end
      member do
        post :hide
        post :unhide
      end
    end
    concern :freeze do
      collection do
        get :frozen
      end
      member do
        post :freeze
      end
    end

    resource :administrator_session, path: "session"
    resource :administrator, only: [] do
      get :forget_password
      match :verification_code, via: [:get, :post, :patch]
      match :confirm, via: [:post, :patch]

      get :password
      patch :password, action: :update_password
    end

    resources :administrators do
      member do
        post :active
        post :inactive
      end
    end

    resources :users do
      member do
        post :mechanicize

        get :balance
        patch :balance, action: :update_balance
      end
    end
    resources :user_groups, concerns: [:confirm]
    resources :mechanics, concerns: [:hide] do
      resources :orders

      collection do
        get :import
        post :import, action: :create_import
      end

      member do
        post :clientize
      end
    end
    resources :merchants, concerns: [:confirm] do
      resources :orders

      member do
        post :active
        post :inactive
        get :settings
        post :settings, action: :update_settings
      end
    end
    resources :orders
    resources :refunds, concerns: [:confirm, :freeze]
    resources :withdrawals, concerns: [:confirm, :cancel] do
      collection do
        get :settings
        post :settings, action: :update_settings
      end
    end
    namespace :settings do
      resources :skills
      resources :brands
      resources :series, except: :show
    end

    root to: "users#index"
  end

  root to: "users#show"
end

app/controllers/admin/merchants_controller.rb
class Admin::MerchantsController < Admin::ApplicationController
  before_action :redirect_user
  before_action :find_merchant, except: [ :index, :confirmed ]

  def index
    @merchants = Store.merchants.unconfirmeds
  end

  def confirmed
    @confirmed = true
    @merchants = Store.merchants.confirmeds
  end

  def confirm
    @merchant.confirm!
    redirect_to_referer!
  end

  def active
    @merchant.active!
    redirect_to_referer!
  end

  def inactive
    @merchant.inactive!
    redirect_to_referer!
  end

  def destroy
    @merchant.destroy
    redirect_to_referer!
  end

  def update_settings
    ActiveRecord::Base.transaction do
      settings = @merchant.settings
      params = setting_params
      use_system_commission_percent = params.delete :use_system_commission_percent
      if ["0", 0, false].include? use_system_commission_percent
        settings[:use_system_commission_percent] = false
        params.each do |key, value|
          settings[key] = value
        end
      else
        settings[:use_system_commission_percent] = true
        params.each do |key, value|
          settings.destroy key rescue nil
        end
      end
    end
    redirect_to settings_admin_merchant_path(@merchant)
  end

  private

    def find_merchant
      @merchant = Store.find(params[:id])
    end

    def setting_params
      params.require(:store_scoped_settings).permit(:use_system_commission_percent,
        :commission_percent, :mobile_commission_percent, :client_commission_percent,
        :mechanic_commission_percent)
    end

end

app/controllers/merchants/admin/application_controller.rb
class Merchants::Admin::ApplicationController <  Merchants::ApplicationController
  before_action :redirect_user

  private

    def redirect_user
      if current_merchant && current_merchant.dispatcher?
        flash[:error] = "派单员无法访问此页面！"
        redirect_to merchants_root_path
      end
    end

end

app/controllers/merchants/admin/merchants_controller.rb
class Merchants::Admin::MerchantsController < Merchants::Admin::ApplicationController
  before_action :find_merchant, except: [ :index, :new, :create ]

  def index
    @merchants = merchant_klass.all
  end

  def new
    @merchant = merchant_klass.new
  end

  def create
    @merchant = merchant_klass.new(merchant_params)
    @merchant.skip_send_verification_code
    if @merchant.save
      redirect_to merchants_admin_merchants_path
    else
      render :new
    end
  end

  def update
    if @merchant.update_attributes(merchant_params)
      redirect_to merchants_admin_merchants_path
    else
      render :edit
    end
  end

  def active
    @merchant.active!
    redirect_to_referer!
  end

  def inactive
    @merchant.inactive!
    redirect_to_referer!
  end

  private

    def find_merchant
      @merchant = merchant_klass.find(params[:id])
    end

    def merchant_klass
      Merchant.where(user_id: current_store)
    end

    def merchant_params
      params.require(:merchant).permit(:mobile, :nickname, :address, :password,
        :password_confirmation, :role)
    end
end

app/controllers/merchants/admin/orders_controller.rb
class Merchants::Admin::OrdersController < Merchants::Admin::ApplicationController
  before_action :find_order, except: [ :index ]

  def index
    @state = if %w(pendeds paids workings settleds refundeds revieweds closeds).include? params[:state]
        params[:state].to_sym
      else
        :pendeds
      end
    @orders = order_klass.send(@state)
  end

  def close
    @order.close!
    flash[:notice] = "订单标记为已结算！"
    redirect_to current_order_path
  end

  private

    def current_order_path
      merchants_admin_order_path(@order)
    end

    def find_order
      @order = order_klass.find(params[:id])
    end

    def order_klass
      Order.where(user_id: current_store)
    end
end

app/controllers/merchants/admin/recharges_controller.rb
class Merchants::Admin::RechargesController < Merchants::Admin::ApplicationController
  skip_before_action :verify_authenticity_token, :authenticate!, :redirect_user, only: [ :notify ]
  before_action :find_recharge, except: [ :index, :new, :create, :notify ]

  def index
    redirect_to new_merchants_admin_recharge_path
  end

  def new
    @recharge = recharge_klass.new
  end

  def create
    @recharge = recharge_klass.new(recharge_params)
    if @recharge.save
      case params[:format]
      when "alipay"
        response = Ali.recharge @recharge
        redirect_to response
      when "weixin"
        response = Weixin.recharge_qrcode @recharge
        if response.success?
          @code_url = response["code_url"]
          flash.now[:notice] = "正在创建支付订单..."
        else
          @recharge.pay! :weixin if response["err_code"] == "ORDERPAID"
          flash[:error] = "微信支付：#{response["err_code_des"]}"
          redirect_to merchants_root_path
        end
      else
        flash[:error] = "未知支付类型"
        redirect_to new_merchants_admin_recharge_path
      end
    else
      render :new
    end
  end

  def result
    case params[:format]
    when "js"
      return
    when "alipay", "weixin"
      notify_params = params.except(*request.path_parameters.keys)
      if Alipay::Notify.verify?(notify_params)
        @recharge.pay! :alipay, notify_params[:trade_no]
      end

      if @recharge.paid?
        flash[:success] = "成功支付订单！"
        redirect_to merchants_root_path
      else
        flash.now[:notice] = "正在查询订单支付结果..."
      end
    else
      flash[:error] = "未知支付类型"
      redirect! :payment, current_order_path
    end
  end

  def notify
    case params[:format]
    when "alipay"
      notify_params = params.except(*request.path_parameters.keys)
      if Alipay::Notify.verify?(notify_params)
        case notify_params[:notify_type]
        when "trade_status_sync"
          Recharge.find(params[:id]).pay! :alipay, notify_params[:trade_no]
          render nothing: true
        else
          render text: "未知支付类型", status: 400
        end
      else
        render text: "签名校验失败", status: 400
      end
    when "weixin"
      notify_params = Hash.from_xml(request.body.read)["xml"]

      if WxPay::Sign.verify?(notify_params)
        # find your order and process the post-paid logic.
        Recharge.find(params[:id]).pay! :weixin, notify_params[:transaction_id]
        render :xml => {return_code: "SUCCESS"}.to_xml(root: 'xml', dasherize: false)
      else
        render :xml => {return_code: "FAIL", return_msg: "签名失败"}.to_xml(root: 'xml', dasherize: false)
      end
    else
      render text: "未知支付类型", status: 400
    end
  end

  private

    def find_recharge
      @recharge = recharge_klass.find(params[:id])
    end

    def recharge_klass
      Recharge.where(merchant_id: current_merchant, store_id: current_store)
    end

    def recharge_params
      params.require(:recharge).permit(:amount)
    end
end

app/controllers/merchants/admin/stores_controller.rb
class Merchants::Admin::StoresController < Merchants::Admin::ApplicationController

  def update
    if current_store.update_attributes(store_params)
      redirect_to merchants_root_path
    else
      render :edit
    end
  end

  private

    def store_params
      params.require(:store).permit(:nickname, :qq, :hotline, :avatar)
    end
end

app/controllers/merchants/application_controller.rb
class Merchants::ApplicationController < ActionController::Base
  include RedirectionHelper

  layout "merchants"

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_merchant_session, :current_merchant, :current_store
  before_action :authenticate!

  private

    def current_merchant_session
      return @current_merchant_session if defined?(@current_merchant_session)
      @current_merchant_session = MerchantSession.find
    end

    def current_merchant
      return @current_merchant if defined?(@current_merchant)
      @current_merchant = current_merchant_session && current_merchant_session.merchant
    end

    def current_store
      return @current_store if defined?(@current_store)
      @current_store = current_merchant && current_merchant.store
    end

    def authenticate!
      if !current_merchant_session || !current_merchant
        set_redirect_original_url :authenticate
        redirect_to new_merchants_merchant_session_path
      else
        clear_redirect :authenticate
      end
    end
end

app/controllers/merchants/bids_controller.rb
class Merchants::BidsController < Merchants::ApplicationController
  before_action :find_order
  before_action :find_bid, only: [ :show, :pick ]

  def pick
    if @order.pick!(@bid)
      flash[:success] = "成功选中技师！"
      redirect_to merchants_order_path @order
    else
      flash.now[:error] = "订单已失效..."
      render :show
    end
  end

  private

    def find_order
      @order = Order.find(params[:order_id])
    end

    def find_bid
      @bid = bid_klass.find(params[:id])
    end

    def bid_klass
      Bid.where(order_id: params[:order_id])
    end

    def bid_params
      params.require(:bid).permit(:markup_price)
    end
end

app/controllers/merchants/hosting/orders_controller.rb
class Merchants::Hosting::OrdersController < Merchants::OrdersController
  before_action :redirect_user

  def index
    @state = if %w(unassigneds assigneds workings finisheds).include? params[:state]
        params[:state].to_sym
      else
        :unassigneds
      end
    @orders = order_klass.send(@state)
  end

  def update_pick
    mechanic_id = params[:order][:mechanic_id]
    if mechanic_id.present?
      remark = params[:order][:remark]
      @order.update_attribute(:remark, remark) if remark
      mechanic = Mechanic.find(mechanic_id)
      @order.repick! mechanic
      redirect_to current_order_path
    else
      @order.remark = params[:order][:remark]
      @order.errors.add :base, "请选择一个技师"
      render :pick
    end
  end

  def update_procedure_price
    if @order.update_attributes(procedure_price_order_params)
      redirect_to current_order_path
    else
      render :procedure_price
    end
  end

  private

    def current_order_path
      merchants_hosting_order_path(@order)
    end

    def redirect_pending
      if order = order_klass.confirmings.first
        flash[:notice] = "您有一条需要确认完工的订单..."
        redirect_to merchants_hosting_order_path(order)
      end
    end

    def order_klass
      Order.hostings
    end

    def find_order
      @order = order_klass.find(params[:id])
    end

    alias_method :find_store_order, :find_order

    def redirect_user
      unless current_store.host?
        flash[:error] = "无法访问此页面！"
        redirect_to merchants_root_path
      end
    end

    def remark_order_params
      params.require(:order).permit(:hosting_remark)
    end

    def procedure_price_order_params
      params.require(:order).permit(:procedure_price)
    end
end

app/controllers/merchants/mechanics_controller.rb
class Merchants::MechanicsController < Merchants::ApplicationController
  before_action :find_mechanic, only: [:show, :reviews, :remark, :update_remark, :skill]

  def index
    @state = if %w(followeds).include? params[:state]
        params[:state].to_sym
      end
  end

  def follow
    current_store.follow!(params[:id])
    redirect_to_referer!
  end

  def unfollow
    current_store.unfollow!(params[:id])
    redirect_to_referer!
  end

  def reviews
    @reviews = @mechanic.orders
  end

  def update_remark
    @fellowship = Fellowship.where(mechanic_id: @mechanic.id, user_id: current_merchant.user_id).first

    if @fellowship && @fellowship.update_attributes(fellowship_params)
      flash[:notice] = "成功更新备注！"
      redirect_to merchants_mechanic_path(@mechanic)
    else
      render :remark
    end
  end

  private
    def find_mechanic
      @mechanic = Mechanic.find(params[:id])
    end

    def fellowship_params
      params.require(:fellowship).permit(:remark)
    end
end

app/controllers/merchants/notes_controller.rb
class Merchants::NotesController < Merchants::ApplicationController
  before_action :find_note

  def update
    if @note.update_attributes(note_params)
      flash[:notice] = "成功更新记事本！"
      redirect_to merchants_note_path
    else
      render :show
    end
  end

  private

    def find_note
      @note = current_store.notes.first_or_create
    end

    def note_params
      params.require(:note).permit(:content)
    end
end

app/controllers/merchants/stores_controller.rb
class Merchants::StoresController < Merchants::ApplicationController
end

app/views/admin/merchants/confirmed.html.erb
<h3 class="page-header">商家管理</h3>

<div class="row">
  <div class="col-md-2 col-xs-4">
    <ul class="nav nav-pills nav-stacked">
      <li><%= link_to "申请列表", admin_merchants_path %></li>
      <li class="active"><%= link_to "商家列表", confirmed_admin_merchants_path %></li>
    </ul>
  </div>

  <% @merchants = @merchants.includes(:merchant) %>

  <div class="col-md-10 col-xs-8">
    <%= index_for [ :admin, @merchants ], class: "table table-hover data-tables" do |i| %>
      <%= i.fields_for :merchant, model: Merchant do |ii| %>
        <%= ii.attribute :nickname %>
        <%= ii.attribute :mobile %>
      <% end %>

      <%= i.attribute :nickname %>
      <%= i.attribute :qq %>

      <%= i.attribute :available_orders_count %>
      <%= i.attribute :total_cost %>

      <%= i.actions do |a| %>
        <%= a.action_link :show, url: admin_merchant_path(i.object) %>
        <% if i.object.active %>
          <%= a.action_link :inactive, url: inactive_admin_merchant_path(i.object), method: :post, confirm: "你确定要锁定这个账户？" %>
        <% else %>
          <%= a.action_link :active, url: active_admin_merchant_path(i.object), method: :post, confirm: "你确定要激活这个账户？" %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/admin/merchants/index.html.erb
<h3 class="page-header">商家管理</h3>

<div class="row">
  <div class="col-md-2 col-xs-4">
    <ul class="nav nav-pills nav-stacked">
      <li class="active"><%= link_to "申请列表", admin_merchants_path %></li>
      <li><%= link_to "商家列表", confirmed_admin_merchants_path %></li>
    </ul>
  </div>

  <% @merchants = @merchants.includes(:merchant) %>

  <div class="col-md-10 col-xs-8">
    <%= index_for [ :admin, @merchants ], class: "table table-hover data-tables" do |i| %>
      <%= i.fields_for :merchant, model: Merchant do |ii| %>
        <%= ii.attribute :nickname %>
        <%= ii.attribute :mobile %>
      <% end %>

      <%= i.attribute :nickname %>
      <%= i.attribute :qq %>

      <%= i.actions do |a| %>
        <%= a.action_link :confirm, url: confirm_admin_merchant_path(i.object), method: :post, confirm: "你确定要通过这条申请？" %>
        <%= a.action_link :destroy, url: admin_merchant_path(i.object), method: :delete, confirm: t("index_for.actions.confirmation") %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/admin/merchants/settings.html.erb
<h3 class="page-header">商家详情 #<%= @merchant.id %></h3>

<div class="row">
  <div class="col-md-2 col-xs-4">
    <ul class="nav nav-pills nav-stacked">
      <li><%= link_to "商家详情", admin_merchant_path(@merchant) %></li>
      <li class="active"><%= link_to "佣金设置", settings_admin_merchant_path(@merchant) %></li>
    </ul>
  </div>

  <div class="col-md-7 col-xs-8">
    <%= bootstrap_simple_form_for(@merchant.settings, url: settings_admin_merchant_path(@merchant)) do |f| %>
      <%= f.error_messages %>

      <% use_system_commission_percent = @merchant.settings.use_system_commission_percent %>
      <%= f.input :use_system_commission_percent, as: :boolean %>
      <%= f.input :commission_percent, as: :float, readonly: use_system_commission_percent %>
      <%= f.input :mobile_commission_percent, as: :float, readonly: use_system_commission_percent %>
      <%= f.input :client_commission_percent, as: :float, readonly: use_system_commission_percent %>
      <%= f.input :mechanic_commission_percent, as: :float, readonly: use_system_commission_percent %>

      <%= f.button :submit, "确定", class: "btn-primary pull-right" %>
    <% end %>
  </div>

  <script type="text/javascript">
    (function() {
      $("#store_scoped_settings_use_system_commission_percent").change(function(event) {
        var use_system_commission_percent = $(this).is(":checked");
        $("#store_scoped_settings_commission_percent, #store_scoped_settings_mobile_commission_percent, #store_scoped_settings_client_commission_percent, #store_scoped_settings_mechanic_commission_percent").attr("readonly", use_system_commission_percent);
      })
    })();
  </script>
</div>

app/views/admin/merchants/show.html.erb
<h3 class="page-header">商家详情 #<%= @merchant.id %></h3>

<div class="row">
  <div class="col-md-2 col-xs-4">
    <ul class="nav nav-pills nav-stacked">
      <li class="active"><%= link_to "商家详情", admin_merchant_path(@merchant) %></li>
      <li><%= link_to "佣金设置", settings_admin_merchant_path(@merchant) %></li>
    </ul>
  </div>

  <div class="col-md-10 col-xs-8">

    <div class="row">
      <div class="col-sm-3 text-right">
        <%= image_tag(@merchant.avatar.url(:thumb)) %>
      </div>

      <div class="col-sm-9">
        <%= show_for @merchant, class: "dl-horizontal" do |i| %>
          <%= i.fields_for :merchant, model: Merchant do |ii| %>
            <%= ii.attribute :nickname %>
            <%= ii.attribute :mobile %>
          <% end %>

          <%= i.attribute :nickname %>
          <%= i.attribute :qq %>
          <%= i.attribute :balance %>

          <%= i.attribute :available_orders_count %>
          <%= i.attribute :total_cost %>

        <% end %>
      </div>
    </div>

  </div>
</div>

<div class="pull-right">
  <%= link_to "相关订单", admin_merchant_orders_path(@merchant), class: "btn btn-primary" %>
</div>