config/routes.rb
Rails.application.routes.draw do

  options = Rails.env.production? ? { path: "", constraints: { subdomain: 'es' }} : {}

  concern :pick do
    member do
      get :pick
      patch :pick, action: :update_pick
    end
  end

  concern :review do
    member do
      get :review
      patch :review, action: :update_review
    end
  end

  namespace :merchants, options do
    resource :merchant_session, path: "session"
    resource :merchant do
      get :forget_password
      match :verification_code, via: [:get, :post, :patch]
      match :confirm, via: [:post, :patch]

      get :password
      patch :password, action: :update_password
    end

    resource :note

    resources :orders, concerns: [:pick, :review] do
      resources :bids do
        member do
          get :pick
        end
      end

      collection do
        get :"pay/:id", action: :pay, as: :pay
      end

      member do
        post :pend
        post :cancel
        match :refund, via: [:get, :patch]
        match :notify, via: [:get, :post]
        get :result
        post :confirm
        post :rework
        get :revoke
        get :remark
        patch :remark, action: :update_remark
      end
    end

    namespace :hosting do
      resources :orders, concerns: [:pick, :review] do
        member do
          match :refund, via: [:get, :patch]
          post :confirm
          post :rework
          get :revoke
          get :remark
          patch :remark, action: :update_remark
          get :procedure_price
          patch :procedure_price, action: :update_procedure_price
        end
      end
    end

    resources :merchants
    resources :mechanics do
      member do
        post :follow
        post :unfollow
        get :remark
        patch :remark, action: :update_remark
        get :reviews
        get :"skills/:skill", action: :skill, as: :skill
      end
    end

    namespace :admin do
      resources :merchants do
        member do
          post :active
          post :inactive
        end
      end
      resources :orders do
        member do
          post :close
        end
      end
      resource :store
      resources :recharges do
        member do
          match :notify, via: [:get, :post]
          get :result
        end
      end
    end

    namespace :store do
      resources :orders
    end
    resource :store

    root to: "orders#new"
  end

  mount WeixinRailsMiddleware::Engine, at: "/"
  resource :user
  resource :user_session, path: "session" do
    post :verification_code
  end
  resource :user_group do
    get :weixin_qr_code
    get :users
  end
  resources :mechanics do
    member do
      get :follow
      get :unfollow
      get :reviews
    end
  end

  resources :orders, concerns: [:review] do
    resources :bids do
      member do
        get :pick
      end
    end

    collection do
      get :"pay/:id", action: :pay, as: :pay
      get :not_found
    end

    member do
      get :cancel
      get :refund
      post :notify
      get :result
      get :work
      patch :finish
      get :confirm
    end
  end

  resources :withdrawals

  namespace :admin do
    concern :confirm do
      collection do
        get :confirmed
      end
      member do
        post :confirm
      end
    end
    concern :cancel do
      collection do
        get :canceled
      end
      member do
        post :cancel
      end
    end
    concern :hide do
      collection do
        get :hidden
      end
      member do
        post :hide
        post :unhide
      end
    end
    concern :freeze do
      collection do
        get :frozen
      end
      member do
        post :freeze
      end
    end

    resource :administrator_session, path: "session"
    resource :administrator, only: [] do
      get :forget_password
      match :verification_code, via: [:get, :post, :patch]
      match :confirm, via: [:post, :patch]

      get :password
      patch :password, action: :update_password
    end

    resources :administrators do
      member do
        post :active
        post :inactive
      end
    end

    resources :users do
      member do
        post :mechanicize

        get :balance
        patch :balance, action: :update_balance
      end
    end
    resources :user_groups, concerns: [:confirm]
    resources :mechanics, concerns: [:hide] do
      resources :orders

      collection do
        get :import
        post :import, action: :create_import
      end

      member do
        post :clientize
      end
    end
    resources :merchants, concerns: [:confirm] do
      resources :orders

      member do
        post :active
        post :inactive
        get :settings
        post :settings, action: :update_settings
      end
    end
    resources :orders
    resources :refunds, concerns: [:confirm, :freeze]
    resources :withdrawals, concerns: [:confirm, :cancel] do
      collection do
        get :settings
        post :settings, action: :update_settings
      end
    end
    namespace :settings do
      resources :skills
      resources :brands
      resources :series, except: :show
    end

    root to: "users#index"
  end

  root to: "users#show"
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::ApplicationController
  before_action :find_order, except: [ :index ]

  def index
    @orders = if params[:mechanic_id]
        @mechanic = Mechanic.where(user_id: params[:mechanic_id]).first!
        @mechanic.orders
      elsif params[:merchant_id]
        @merchant = Merchant.where(user_id: params[:merchant_id]).first!
        @merchant.orders
      else
        Order.all
      end
  end

  private

    def find_order
      @order = Order.find(params[:id])
    end
end

app/controllers/merchants/admin/orders_controller.rb
class Merchants::Admin::OrdersController < Merchants::Admin::ApplicationController
  before_action :find_order, except: [ :index ]

  def index
    @state = if %w(pendeds paids workings settleds refundeds revieweds closeds).include? params[:state]
        params[:state].to_sym
      else
        :pendeds
      end
    @orders = order_klass.send(@state)
  end

  def close
    @order.close!
    flash[:notice] = "订单标记为已结算！"
    redirect_to current_order_path
  end

  private

    def current_order_path
      merchants_admin_order_path(@order)
    end

    def find_order
      @order = order_klass.find(params[:id])
    end

    def order_klass
      Order.where(user_id: current_store)
    end
end

app/controllers/merchants/admin/stores_controller.rb
class Merchants::Admin::StoresController < Merchants::Admin::ApplicationController

  def update
    if current_store.update_attributes(store_params)
      redirect_to merchants_root_path
    else
      render :edit
    end
  end

  private

    def store_params
      params.require(:store).permit(:nickname, :qq, :hotline, :avatar)
    end
end

app/controllers/merchants/hosting/orders_controller.rb
class Merchants::Hosting::OrdersController < Merchants::OrdersController
  before_action :redirect_user

  def index
    @state = if %w(unassigneds assigneds workings finisheds).include? params[:state]
        params[:state].to_sym
      else
        :unassigneds
      end
    @orders = order_klass.send(@state)
  end

  def update_pick
    mechanic_id = params[:order][:mechanic_id]
    if mechanic_id.present?
      remark = params[:order][:remark]
      @order.update_attribute(:remark, remark) if remark
      mechanic = Mechanic.find(mechanic_id)
      @order.repick! mechanic
      redirect_to current_order_path
    else
      @order.remark = params[:order][:remark]
      @order.errors.add :base, "请选择一个技师"
      render :pick
    end
  end

  def update_procedure_price
    if @order.update_attributes(procedure_price_order_params)
      redirect_to current_order_path
    else
      render :procedure_price
    end
  end

  private

    def current_order_path
      merchants_hosting_order_path(@order)
    end

    def redirect_pending
      if order = order_klass.confirmings.first
        flash[:notice] = "您有一条需要确认完工的订单..."
        redirect_to merchants_hosting_order_path(order)
      end
    end

    def order_klass
      Order.hostings
    end

    def find_order
      @order = order_klass.find(params[:id])
    end

    alias_method :find_store_order, :find_order

    def redirect_user
      unless current_store.host?
        flash[:error] = "无法访问此页面！"
        redirect_to merchants_root_path
      end
    end

    def remark_order_params
      params.require(:order).permit(:hosting_remark)
    end

    def procedure_price_order_params
      params.require(:order).permit(:procedure_price)
    end
end

app/controllers/merchants/orders_controller.rb
class Merchants::OrdersController < Merchants::ApplicationController
  skip_before_action :verify_authenticity_token, :authenticate!, only: [ :notify ]
  before_action :find_order, except: [ :index, :new, :create, :notify, :remark, :update_remark ]
  before_action :find_store_order, only: [ :remark, :update_remark ]
  before_action :redirect_pending, only: [ :new, :index ]

  helper_method :fetch_redirect, :current_order_path

  def index
    @state = if %w(pendeds paids workings finisheds).include? params[:state]
        params[:state].to_sym
      else
        :pendeds
      end
    @orders = order_klass.send(@state)
  end

  def new
    @order = order_klass.new
  end

  def create
    @order = order_klass.new(order_params)
    if @order.save
      if @order.appointing?
        redirect_to pick_merchants_order_path(@order)
      elsif @order.pending?
        redirect_to merchants_order_bids_path(@order)
      else
        redirect_to current_order_path
      end
    else
      render :new
    end
  end

  def pick
    set_redirect_referer :pick_mechanic
  end

  def update_pick
    if mechanic_id = params[:order][:mechanic_id]
      remark = params[:order][:remark]
      @order.update_attribute(:remark, remark) if remark
      mechanic = Mechanic.find(mechanic_id)
      if @order.assigned?
        @order.repick! mechanic
      else
        @order.pick! mechanic
      end
      redirect! :pick_mechanic, current_order_path
    else
      @order.remark = params[:order][:remark]
      @order.errors.add :base, "请选择一个技师"
      render :pick
    end
  end

  def cancel
    @order.cancel!
    flash[:notice] = "订单已取消！"
    redirect_to_referer!
  end

  def pend
    @order.pend!
    flash[:notice] = "订单延后付款！"
    redirect_to_referer!
  end

  def pay
    set_redirect_referer :payment
    case params[:format]
    when "alipay"
      response = Ali.payment @order
      redirect_to response
    when "weixin"
      response = Weixin.payment_qrcode @order
      if response.success?
        @code_url = response["code_url"]
        flash.now[:notice] = "正在创建支付订单..."
      else
        @order.pay! :weixin if response["err_code"] == "ORDERPAID"
        flash[:error] = "微信支付：#{response["err_code_des"]}"
        redirect! :payment, current_order_path
      end
    when "balance"
      if @order.price > current_store.balance
        flash[:error] = "店铺余额不足，请使用其他方式支付"
        redirect! :payment, current_order_path
      else
        render :balance
      end
    else
      flash[:error] = "未知支付类型"
        redirect! :payment, current_order_path
    end
  end

  def notify
    case params[:format]
    when "alipay"
      notify_params = params.except(*request.path_parameters.keys)
      if Alipay::Notify.verify?(notify_params)
        case notify_params[:notify_type]
        when "trade_status_sync"
          Order.find(params[:id]).pay! :alipay, notify_params[:trade_no]
          render nothing: true
        when "batch_refund_notify"
          Order.find(params[:id]).refund!
          render nothing: true
        else
          render text: "未知支付类型", status: 400
        end
      else
        render text: "签名校验失败", status: 400
      end
    when "weixin"
      notify_params = Hash.from_xml(request.body.read)["xml"]

      if WxPay::Sign.verify?(notify_params)
        # find your order and process the post-paid logic.
        Order.find(params[:id]).pay! :weixin, notify_params[:transaction_id]
        render :xml => {return_code: "SUCCESS"}.to_xml(root: 'xml', dasherize: false)
      else
        render :xml => {return_code: "FAIL", return_msg: "签名失败"}.to_xml(root: 'xml', dasherize: false)
      end
    else
      render text: "未知支付类型", status: 400
    end
  end

  def result
    case params[:format]
    when "js"
      return
    when "alipay", "weixin"
      notify_params = params.except(*request.path_parameters.keys)
      if Alipay::Notify.verify?(notify_params)
        @order.pay! :alipay, notify_params[:trade_no]
      end

      if @order.paid?
        flash[:success] = "成功支付订单！"
        redirect! :payment, current_order_path
      else
        flash.now[:notice] = "正在查询订单支付结果..."
      end
    when "balance"
      @order.pay! :balance
      redirect! :payment, current_order_path
    else
      flash[:error] = "未知支付类型"
      redirect! :payment, current_order_path
    end
  end

  def refund
    if @order.paid? || @order.working? || @order.confirming?
      if @order.paid?
        reason = :user_cancel
      else
        reason = :merchant_revoke
        @order.update_attributes(review_order_params)
      end

      if [ :alipay, :weixin, :balance ].include? @order.pay_type
        flash[:notice] = "退款申请已提交，等待管理员审核..."
        @order.refunding! reason
      elsif @order.offline?
        @order.refund! reason
      else
        flash[:error] = "未知支付类型"
      end
    else
      flash[:error] = "订单状态错误！"
    end
    redirect! :revoke_order, request.referer
  end

  def remark
    set_redirect_referer :remark_order
  end

  def update_remark
    if @order.update_attributes(remark_order_params)
      redirect! :remark_order, current_order_path
    else
      render :remark
    end
  end

  def rework
    @order.rework!
    flash[:notice] = "订单申请返工！"
    redirect_to_referer!
  end

  def confirm
    @order.confirm!
    flash[:notice] = "订单确认完工！"
    redirect_to_referer!
  end

  def revoke
    set_redirect_referer :revoke_order
  end

  def review
    set_redirect_referer :review_order
  end

  def update_review
    if @order.update_attributes(review_order_params)
      @order.review!
      redirect! :review_order, current_order_path
    else
      render :review
    end
  end

  private

    def current_order_path
      merchants_order_path(@order)
    end

    def redirect_pending
      if order = unhosting_order_klass.pendings.first
        if order.appointing?
          flash[:notice] = "您有一条需要指派技师的订单..."
          redirect_to merchants_order_path(order)
        else
          flash[:notice] = "您有一条竞价中的订单..."
          redirect_to merchants_order_bids_path(order)
        end
      elsif order = unhosting_order_klass.payings.first
        flash[:notice] = "您有一条需要支付的订单..."
        redirect_to merchants_order_path(order)
      elsif order = unhosting_order_klass.confirmings.first
        flash[:notice] = "您有一条需要确认完工的订单..."
        redirect_to merchants_order_path(order)
      end
    end

    def find_order
      @order = if current_merchant.admin?
          admin_order_klass.find(params[:id])
        else
          order_klass.find(params[:id])
        end
    end

    def find_store_order
      @order = admin_order_klass.find(params[:id])
    end

    def admin_order_klass
      Order.where(user_id: current_store)
    end

    def order_klass
      Order.where(user_id: current_store, merchant_id: current_merchant)
    end

    def unhosting_order_klass
      Order.where(user_id: current_store, merchant_id: current_merchant, hosting: false)
    end

    def order_params
      params.require(:order).permit(:address, :appointment, :skill_cd,
        :brand_cd, :series_cd, :quoted_price, :remark, :merchant_remark,
        :custom_location, :lbs_id, :province_cd, :city_cd, :professionality,
        :timeliness, :review, :contact_mobile, :contact_nickname, :hosting,
        :appointing, :offline)
    end

    def review_order_params
      params.require(:order).permit(:professionality, :timeliness, :review)
    end

    def remark_order_params
      params.require(:order).permit(:merchant_remark)
    end

end

app/controllers/merchants/store/orders_controller.rb
class Merchants::Store::OrdersController < Merchants::ApplicationController
  before_action :find_order, except: [ :index ]

  def index
    @state = if %w(pendeds paids workings settleds refundeds).include? params[:state]
        params[:state].to_sym
      else
        :pendeds
      end
    @orders = order_klass.send(@state)
  end

  private

    def current_order_path
      merchants_store_order_path(@order)
    end

    def find_order
      @order = order_klass.find(params[:id])
    end

    def order_klass
      Order.where(user_id: current_store)
    end
end

app/controllers/merchants/stores_controller.rb
class Merchants::StoresController < Merchants::ApplicationController
end

app/views/merchants/store/orders/index.html.erb
<h3 class="page-header">订单管理</h3>

<%
  def order_state_link_to state, text
    link = link_to text, merchants_store_orders_path(state: state)
    class_name = (@state == state) ? "active" : ""
    %{<li class="#{class_name}">#{link}</li>}.html_safe
  end
%>

<div class="row">
  <div class="col-md-2 col-xs-4">
    <ul class="nav nav-pills nav-stacked">
      <%= order_state_link_to :pendeds, "待付款" %>
      <%= order_state_link_to :paids, "待服务" %>
      <%= order_state_link_to :workings, "服务中" %>
      <%= order_state_link_to :settleds, "已完成" %>
      <%= order_state_link_to :refundeds, "已退款" %>
    </ul>
  </div>

  <% @orders = @orders.includes(:merchant, :mechanic_user) %>

  <div class="col-md-10 col-xs-8">
    <%= index_for [ :merchants, :store, @orders ], class: "table table-hover data-tables" do |i| %>
      <%= i.attribute :merchant_nickname %>
      <%= i.attribute :contact_nickname %>
      <%= i.attribute :contact_mobile %>
      <%= i.attribute :appointment, format: :short %>
      <%= i.attribute :finish_working_at, format: :short if %i(settleds revieweds closeds).include? @state %>
      <%= i.attribute :skill %>
      <%= i.attribute :price %>
      <%= i.attribute :offline? %>
      <%= i.attribute :mechanic_nickname %>

      <%= i.actions :show %>
    <% end %>
  </div>
</div>

app/views/merchants/store/orders/show.html.erb
<h3 class="page-header">
  订单详情 #<%= @order.id %>
  <small>
    <% if @order.canceled? %>
      <%= te @order, :state %> - <%= te @order, :cancel %>
    <% elsif @order.refunded? %>
      <%= te @order, :state %> - <%= te @order, :refund %>
    <% else %>
      <%= te @order, :state %>
    <% end %>
  </small>
</h3>

<div class="row">
  <div class="col-sm-6">
    <h4 class="col-sm-offset-1">交易信息</h4>

    <%= show_for @order, class: "dl-horizontal" do |i| %>
      <%= i.attribute :merchant_nickname %>
      <%= i.attribute :merchant_mobile %>
      <%= i.attribute :contact_nickname %>
      <%= i.attribute :contact_mobile %>
      <%= i.attribute :state do |order| %>
        <% if order.canceled? %>
          <%= te order, :state %> - <%= te order, :cancel %>
        <% elsif order.refunded? %>
          <%= te order, :state %> - <%= te order, :refund %>
        <% else %>
          <%= te order, :state %>
        <% end %>
      <% end %>

      <%= i.attribute :skill %>
      <%= i.attribute :brand %>
      <%= i.attribute :series %>
      <%= i.attribute :created_at, format: :long %>
      <%= i.attribute :start_working_at, format: :long %>
      <%= i.attribute :finish_working_at, format: :long %>
      <%= i.attribute :remark %>
      <%= i.attribute :merchant_remark %>
    <% end %>
  </div>

  <div class="col-sm-6">
    <h4 class="col-sm-offset-1">价格信息</h4>

    <%= show_for @order, class: "dl-horizontal" do |i| %>
      <%= i.attribute :price, label: "总价" %>
      <%= i.attribute :quoted_price %>
      <%= i.attribute :markup_price %>
      <%= i.attribute :offline? %>
    <% end %>
  </div>

</div>

<div class="pull-right">
  <%= link_to "修改商户备注", remark_merchants_order_path(@order), class: "btn btn-primary" %>
</div>

<% if @order.assigned? %>

  <h3 class="page-header">技师信息</h3>

  <div class="row">
    <div class="col-sm-3 text-right">
      <%= image_tag(@order.mechanic.user.avatar.url(:thumb)) %>
    </div>

    <div class="col-sm-9">
      <%= show_for @order.mechanic, class: "dl-horizontal" do |i| %>
        <%= i.attribute :user_nickname %>
        <%= i.attribute :user_mobile unless @order.hosting? %>
        <%= i.attribute :user_address %>
        <%= i.attribute :description %>
        <%= i.attribute :available_orders_count %>
        <%= i.attribute :professionality_average %>
        <%= i.attribute :timeliness_average %>
      <% end %>
    </div>
  </div>
<% end %>

<% if @order.has_attach? %>
  <h3 class="page-header">施工凭证 <small>点击施工照片查看原图</small></h3>
  <div class="images">
    <%= link_to @order.mechanic_attach_1.url(:original) do %>
      <%= image_tag @order.mechanic_attach_1.url(:thumb), class: "img-rounded" %>
    <% end if @order.mechanic_attach_1.present? %>
    <%= link_to @order.mechanic_attach_2.url(:original) do %>
      <%= image_tag @order.mechanic_attach_2.url(:thumb), class: "img-rounded" %>
    <% end if @order.mechanic_attach_2.present? %>
  </div>
<% end %>

<% case @order.state %>
<% when :pended %>
  <div class="pull-right">
    <%= link_to "余额支付", pay_merchants_orders_path(@order, format: :balance), class: "btn btn-primary" %>
    <%#= link_to "微信支付", pay_merchants_orders_path(@order, format: :weixin), class: "btn btn-primary" %>
    <%= link_to "支付宝支付", pay_merchants_orders_path(@order, format: :alipay), class: "btn btn-primary" %>
  </div>
<% when :reviewed %>
  <div class="pull-right">
    <%= link_to "完成结算", close_merchants_admin_order_path(@order), method: :post, class: "btn btn-primary" %>
  </div>
<% end %>